version: '3.4'

services:

  pokemoncache:
    container_name: pokemoncache
    restart: always
    ports:
      - "6379:6379"

  pokemon.api:
    container_name: pokemon.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "RedisOptions:ConnectionString=pokemoncache:6379"
    depends_on:
      - pokemoncache
    ports:
      - "8001:80"