version: '3.4'
services:
 
  pokemon.api:
    image: ${DOCKER_REGISTRY-}pokemonapi
    build:
      context: .
      dockerfile: Pokemon.Api/Dockerfile

  pokemoncache:
    image: redis:alpine    
  

