version: ‘3.4’
services:
 
  pokemon.api:
    image: ${DOCKER_REGISTRY-}pokemon
    build:
      context: .
      dockerfile: /src/Pokemon.Api/Dockerfile

  pokemoncache:
    image: redis:alpine    
  

